spring:
  datasource:
    url: jdbc:h2:file:~/jpashop;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: user1
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.id.optimizer.pooled.prefer_lo: true
      hibernate.id.new_generator_mappings: true
      hibernate:
        # dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        # ]show_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.orm.jdbc.bind: trace














